deshboard/urls.py
from django.urls import path
from . import views


app_name = 'deshboard'


urlpatterns = [
    path('', views.index ,name= 'index')
]

eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls')),
    path('items/', include('item.urls')),
    path('deshboard/', include('deshboard.urls')),
    path('messaging/', include('messaging.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name= 'items'),
    path('add/', views.new, name='add'),
    path('<int:pk>/', views.details, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

mainapp/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .import views
from .forms import SigninForm



app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('signin/', auth_views.LoginView.as_view(template_name='mainapp/signin.html', authentication_form=SigninForm), name='signin'),
    path('logput/', auth_views.LogoutView.as_view(), name='logout'),
]

messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your user name',
        'class': 'w-full py-4 px-6 rounded-xl !outline-none'}))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl !outline-none'}))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl !outline-none'}))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Re-enter password',
        'class': 'w-full py-4 px-6 rounded-xl !outline-none'}))


class SigninForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter user name',
        'class':'w-full py-4 px-6 rounded-xl !outline-none'}))

    password =forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter password',
        'class':'w-full py-4 px-6 rounded-xl !outline-none'}))

mainapp/views.py
from django.shortcuts import render , redirect

from item.models import Category, Items

from .forms import SignupForm , SigninForm

# Create your views here.




def index(request):
    items = Items.objects.filter(is_sold=False)[:12]
    categories = Category.objects.all()
    return render(request, 'mainapp/index.html', {'categoriess': categories,'itemss': items})

# categories & items are same page which without cotation 
# the other 2 which with "" cotation those working in the html file

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/signin/',)
    else:
        form = SignupForm()

    return render(request, 'mainapp/signup.html', {'form': form})

# def signin(request):
#     form = SigninForm()
#     return render(request, 'mainapp/signin.html')

def contact(request):
    return render(request, 'mainapp/contact.html')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Online shop {% block title%} {% endblock%}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body >
    <!-- top nav -->
    <nav class="px-10 py-5 border-solid border-2 border-slate-400  flex item-center justify-between">
    <a class="text-xl " href="/">Online Shop</a>
    
    <div class="w-1/2 text-center border-3">
        <form method="get" action="{% url 'item:items' %}">
            <input class="w-1/3 py-2 px-5 rounded-xl" name="query" type="text" value="{{ query }}" placeholder="Search product">
            <button class="px-2 py-2 bg-teal-400 text-white rounded-xl"><span class="material-symbols-outlined">search</span></button>
        </form>
    </div>

    <div class="gap-x-5 flex justify-between">
        <a class="px-2 py-2 rounded-md hover:bg-teal-200"
        href="{% url 'item:add' %}">+items</a>

        <a class="bg-teal-300 px-5 py-2 rounded-md hover:bg-teal-600"
        href="{% url 'item:items' %}">Filter</a>

        {% if request.user.is_authenticated %}
        <a class="bg-teal-400 text-slate-100 px-5 py-2 rounded-md hover:bg-teal-700"
        href="{% url 'messaging:inbox' %}">Messages</a>

        <a class="bg-teal-400 text-slate-100 px-5 py-2 rounded-md hover:bg-teal-700"
        href="{% url 'deshboard:index' %}">goto Daseboard</a>

        <a class="bg-red-300 text-slate-100 px-5 py-2 rounded-md hover:bg-red-700"
        href="{% url 'mainapp:logout' %}">Log out</a>
        
        <h5 class="px-5 py-2 border-2 rounded-xl">Log in by: {{request.user}} </h5>

        {% else %}
        <a class="bg-teal-400 text-slate-100 px-5 py-2 rounded-md hover:bg-teal-700"
        href="{% url 'mainapp:signin' %}">Log in</a>

        <a class="bg-red-300 text-slate-100 px-5 py-2 rounded-md hover:bg-red-500"
        href="{% url 'mainapp:signup' %}">Sign up</a>

        {%endif%}
    </div>
</nav>
{% block content%}

{% endblock %}
</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block title %} {% endblock %}
{% block content %}


<!-- here is the item  -->
<div class="px-5 py-12 bg-gray-200 ml-56">
    <h1 class="mb-5 text-2xl text-center">New Products</h1>
    <div class=" grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-2 ">
        {% for item in itemss %}
        <div>
            <a href="{%url 'item:detail' item.id %}">
                <div class="bg-gray-300 w-76 rounded-2xl">
                    <img class="w-76 h-64 rounded-t-2xl" src="{{ item.image.url}}" alt="">
                    <div>
                        <h2 class="text-center text-xl">{{item.Name}} : {{ item.price}}</h2>
                    </div>
                </div>
            </a>
            
        </div>
        {% endfor %}
    </div>
</div>

<!-- Categoris  -->
<div class="mt-1 px-5 pt-3 bg-gray-100 fixed w-56 h-screen top-20">
    <h1 class="mb-5 text-2xl text-center">New Products</h1>
    <div class="gap-5">
        {% for prod_category in categoriess %}
        <div class="py-2">
            <h2 class=" text-2xl">{{prod_category.Name}} : {{prod_category.items.count}}</h2><!-- this item is models.py >Item > related_name= "items" -->
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

mainapp/templates/mainapp/signin.html
{% extends 'mainapp/base.html' %}
{% block title %}Sign in{% endblock %}

{% block content %}
<div class="bg-teal-100 w-1/2 mx-auto p-5 rounded-xl">
    <h1 class="text-3xl text-center my5">Sign in</h1>
    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-5">
            <label class="inline-block mb-2 text-xl" for="">Email</label><br>
            {{form.username}}
        </div>
        <div>
            <label class="inline-block mb-2 text-xl" for="">Password</label><br>
            {{form.password}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="px-8 py-3 mt-5 rounded-xl bg-teal-300 hover:bg-teal-700 text-slate-100" type="submit">Log in</button>
    </form>
</div>
{% endblock %}

mainapp/templates/mainapp/signup.html
{% extends 'mainapp/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-5 mx-auto p-5 bg-teal-100 rounded-xl">
    <h1 class="mb-5 text-3xl">Sing Up</h1>
    <form method="POST" action=".">
        {% csrf_token %}
        <div>
            <label class="inline-block mb-2 text-xl" for="">User name</label><br>
            {{ form.username }}
        </div>
        <div>
            <label class="inline-block mb-2 text-xl" for="">Email</label><br>
            {{form.email}}
        </div>
        <div>
            <label class="inline-block mb-2 text-xl" for="">Password</label><br>
            {{form.password1}}
        </div>
        <div>
            <label class="inline-block mb-2 text-xl" for="">Re-enter password</label><br>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mt-3 mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="px-8 py-3 mt-5 rounded-xl bg-teal-300 hover:bg-teal-700 text-slate-100" type="submit">Register</button>
    </form>
    
</div>

{% endblock %}