eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls')),
    path('items/', include('item.urls')),
    path('deshboard/', include('deshboard.urls')),
    path('messaging/', include('messaging.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name= 'items'),
    path('add/', views.new, name='add'),
    path('<int:pk>/', views.details, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    Name = models.CharField(max_length=255)

    class Meta:
        ordering = ('Name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.Name
    
class Items(models.Model):
    Name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    # name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='product_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name = 'items', on_delete=models.CASCADE)

    
    class Meta:
        ordering = ['Name']
        verbose_name_plural = 'Items'
    
    def __str__(self):
        return self.Name

item/forms.py
from django import forms

from .models import Items

# for avoide representation we make a class for disegning.
# FORM_INPUT_CLASS = 'w-1/2 px-3 py-2 rounded-xl border'
FORM_INPUT_CLASS = 'w-full text-left text-xl mt-2 px-3 py-2 rounded-xl !outline-none'

class NewItemForm(forms.ModelForm):
    class Meta:
        model= Items
        fields = ('Name', 'category', 'description', 'image','price',)

        widgets ={
            'Name': forms.TextInput(attrs={'class':FORM_INPUT_CLASS}),
            'category': forms.Select(attrs={'class':FORM_INPUT_CLASS}),
            'description': forms.Textarea(attrs={'class':FORM_INPUT_CLASS}),
            'image': forms.FileInput(attrs={'class':FORM_INPUT_CLASS}),
            'price': forms.TextInput(attrs={'class':FORM_INPUT_CLASS}),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model= Items
        fields = ('Name', 'description', 'image','price','is_sold')

        widgets ={
            'Name': forms.TextInput(attrs={'class':FORM_INPUT_CLASS}),
            'description': forms.Textarea(attrs={'class':FORM_INPUT_CLASS}),
            'image': forms.FileInput(attrs={'class':FORM_INPUT_CLASS}),
            'price': forms.TextInput(attrs={'class':FORM_INPUT_CLASS}),
            # 'is_sold': forms.BooleanInput(attrs={'class':FORM_INPUT_CLASS}),
        }

item/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
from django.db.models import Q

# Create your views here.

from . models import Items, Category
def details (request,pk):
    item = get_object_or_404(Items, pk=pk)
    related_items = Items.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[:3]
    return render(request, 'item/detail.html',{'item':item ,'related_items':related_items})


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk = item.id)

    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {'form': form , 'title':'Add new item'})

@login_required
def edit(request, pk):
    item = get_object_or_404(Items, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES,instance=item)
        if form.is_valid():

            item.save()
            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title':'Edit item'
        })
    

@login_required
def delete(request, pk):
    item = get_object_or_404(Items, pk=pk, created_by= request.user)
    item.delete()

    return redirect('deshboard:index')


def items(request):
    items=Items.objects.filter(is_sold=False)
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    query = request.GET.get('query', '')

    if query:
        items = items.filter(Q(Name__icontains= query) | Q(description__icontains= query))

    if category_id:
        items = items.filter(category_id = category_id)


    return render(request, 'item/items.html', {
        'items': items,
        'query':query,
        'categories': categories,
        'category_id':int(category_id),
        })

item/templates/item/detail.html
{% extends 'mainapp/base.html' %}
{% block title %} {{item.Name}}{% endblock %}

{% block content%}

<div class="grid grid-cols-5 gap-5 bg-gray-100">
    <div class="col-span-3 rounded">
        <img class="w-1/2" src="{{  item.image.url  }}" alt="">
    </div>
    <div class="col-span-2 p-5 bg-teal-200 rounded-xl">
        <h1 class="mb-5 text-3xl"> <strong class="font-semibold">{{ item.Name }}</strong></h1>
        <p class="text-xl">Price: {{ item.price }}</p>

        <p><strong>Product Details:</strong><br>
            <span class="">{{ item.description }}</span>
        </p>

        {% if request.user == item.created_by %}
        <div class="mt-5 grid grid-cols-5 gap-5">
            <a href="{% url 'item:edit' item.id %}"
            class="bg-teal-400 text-slate-100 py-2 px-3 rounded-md hover:bg-teal-700">Edit</a>

            <a href="{% url 'item:delete' item.id %}"
            class="bg-red-300 text-slate-100 py-2 px-3 rounded-md hover:bg-red-700"><span class="material-symbols-outlined">delete</span>Delete</a>
        </div>

        {% else %}
        <p class="">Vendor: {{ item.created_by.username }}</p>
        <a href="{% url 'messaging:new' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact with vendor</a>
        {% endif %}

    </div>
    
</div>
<!-- Related items -->

<div class="mt-10 bg-gray-200">
    <h2 class="text-2xl text-center">Related items</h2>
    <div>
        {% for item in related_items %}
        <div class="bg-gray-300 w-76 rounded-2xl">
            <a href="{%url 'item:detail' item.id%}">
                <img src="{{ item.image.url }}" alt="">
                <div>
                    <h2>{{item.Name}}</h2>
                    <p>{{item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

item/templates/item/form.html
{% extends 'mainapp/base.html' %}
{% block title %}/ {{ title }} {% endblock %}

{% block content %}
<h1 class="mb-5 text-2xl text-center">{{title}}</h1>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="w-1/2 mx-auto p-5 bg-red-100 rounded-xl">
        <div class="mx-auto w-full">
            {{ form.as_p }}
        </div>
        
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class="mt-5 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            {% if form.new %}
                Create Item
            {% else %}
                Update Item
            {% endif %}
        </button>
    </div>
</form>



{% endblock%}

item/templates/item/items.html
{% extends 'mainapp/base.html' %}
{% block title %}/ Filter item{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-4">
    <!-- left nav ber -->
    <div class="grid-span-1">
        <p class="font-semibold text-center text-xl ">Category</p>
        <ul class="bg-gray-100">
            {% for category in categories %}
            <li class="px-5 py-2" {% if category.id == category_id %} {% endif %}>
                <a class="text-xl hover:px-5 hover:py-2 hover:bg-teal-300 rounded-r-2xl focus:active"
                href="{% url 'item:items' %}?category={{category.id}}">{{category.Name}}</a>
            </li>
        {% endfor %}
        </ul>
        <!-- <form method="get" action="{% url 'item:items' %}">
            <input name="query" type="text" value="{{ query }}" placeholder="Search product by name or description....">
            <button class="px-2 py-4 mt-2 bg-teal-400 text-white rounded-xl">Search Product</button>
        </form> -->



    </div>

    <div class=" grid col-span-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-2 ">
        {% for item in items %}
        <div class="mt-5">
            <a href="{%url 'item:detail' item.id %}">
                <div class="bg-gray-300 w-76 h-64 rounded-2xl">
                    <img class="w-full h-56 rounded-t-2xl" src="{{ item.image.url}}" alt="">
                    <div>
                        <h2 class="text-center text-xl">{{item.Name}} : {{ item.price}}</h2>
                    </div>
                </div>
            </a>
            
        </div>
        {% endfor %}
    </div>
     
</div>

{% endblock%}